on:
  workflow_dispatch

name: Manual Release and Deploy
jobs:
  manual_release:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: tt151extpack # package name in package.json
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package VS Code extension
        id: package
        uses: nhedger/package-vscode-extension@v1

      - name: Publish VS Code extension artifact
        uses: actions/upload-artifact@v3
        with:
            name: tt151extpack
            path: ${{ steps.package.outputs.packagePath }}

    